### ISSUE TITLE
[BUG]Swapping on Kujira Chain Causes Crashes

### ISSUE THREAD

**Issue by aminsato** [vultisig/vultisig-android#1264]
https://github.com/user-attachments/assets/0d0a282d-044f-4ee2-8ef2-33c19b54207b

```
  java.lang.IllegalStateException: Error getting account
                                                                                                    	at com.vultisig.wallet.data.api.CosmosApiImp.getAccountNumber(CosmosApi.kt:60)
                                                                                                    	at com.vultisig.wallet.data.api.CosmosApiImp$getAccountNumber$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by realpaaao** [comment]
Was missing latest pull. closing
