### ISSUE TITLE
[BUG] Scanning an unrelated QR code using Vultisig Scanner

### ISSUE THREAD

**Issue by aminsato** [vultisig/vultisig-android#1329]
**Describe the bug**
Scanning an unrelated QR code, such as a share vault QR code, with the Vultisig scanner causes the scanner to glitch.

**To Reproduce**
1. One one device, share a vault QR code 
2. one a diffrent device, scan the QR code usign the Vultisig scanner 
3. Observe the glitch in the scanner

**Expected behavior**
An appropiate message should be displayed when an an unrelated QR code is scanned.

**Logcat errors**

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                       at java.util.Collections$SingletonList.get(Collections.java:4861)
                       at com.vultisig.wallet.data.common.DeepLinkHelper.<init>(DeepLinkHelper.kt:12)
                       at com.vultisig.wallet.ui.models.ScanQrViewModel.getFlowType(ScanQrViewModel.kt:68)
                       at com.vultisig.wallet.ui.models.ScanQrViewModel$joinOrSend$1.invokeSuspend(ScanQrViewModel.kt:31)
                                                                                                    	
Failed to navigate to destination
                     java.lang.IllegalArgumentException: Unsupported QR-code flowType: Unknown
                     at com.vultisig.wallet.ui.models.ScanQrViewModel$joinOrSend$1.invokeSuspend(ScanQrViewModel.kt:55)
                     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                     at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:359)
                     at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
                     at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:358)
                     at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:124)
                     at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)

```

**Comment by realpaaao** [comment]
QA done.
